name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  # MacOS 10.15 Binary
  MacOS-binary:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang
          CXX: clang++
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          brew install boost
          mkdir build && cd build
          cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DCMAKE_BUILD_TYPE=Release .. && make crabwise
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${RELEASE_VERSION}"
          prerelease: false
          title: "MacOS 10.15 Build ${RELEASE_VERSION}"
      - uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: ./build/src/crabwise
          asset_name: crabwise
          tag: "${RELEASE_VERSION}"
          overwrite: false
